project_id = "mprqsjlwfdjdnbgamfiu"

[functions.delete-user]
verify_jwt = false

[functions.get-users]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.send-date-change-notification]
verify_jwt = false

[functions.send-event-cancellation]
verify_jwt = false

[functions.send-event-invitations]
verify_jwt = false

[functions.mark-completed-events]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-event-reminder]
verify_jwt = false
